#!/usr/bin/env node
// Build script to embed .lp files as JavaScript string exports
// This generates src/EmbeddedPrograms.js which can be imported via FFI

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const aspRoot = join(projectRoot, '..');

// Files to embed
const files = {
  botc: join(aspRoot, 'botc.lp'),
  tb: join(aspRoot, 'tb.lp'),
  players: join(aspRoot, 'players.lp'),
  types: join(aspRoot, 'types.lp'),
};

// Read and escape content for JS string
function readAndEscape(filepath) {
  const content = readFileSync(filepath, 'utf-8');
  // Use JSON.stringify to properly escape the string
  return JSON.stringify(content);
}

// Generate the JS module
const output = `// Auto-generated by scripts/embed-lp.js - do not edit manually
// Run 'npm run embed-lp' to regenerate

export const botcLp = ${readAndEscape(files.botc)};
export const tbLp = ${readAndEscape(files.tb)};
export const playersLp = ${readAndEscape(files.players)};
export const typesLp = ${readAndEscape(files.types)};
`;

const outputPath = join(projectRoot, 'src', 'EmbeddedPrograms.js');
writeFileSync(outputPath, output);
console.log(`Generated ${outputPath}`);
