#!/usr/bin/env node
// Build script to embed .lp files as JavaScript string exports
// This generates src/EmbeddedPrograms.js which can be imported via FFI

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { dirname, join, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const aspRoot = join(projectRoot, '..');

// Recursively find all .lp files in a directory
function findLpFiles(dir, basePath = dir) {
  const results = [];
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      // Recursively search subdirectories
      results.push(...findLpFiles(fullPath, basePath));
    } else if (entry.endsWith('.lp')) {
      // Use relative path from aspRoot as the key (e.g., "roles/tb/poisoner.lp")
      const relativePath = relative(basePath, fullPath);
      results.push({ path: relativePath, fullPath });
    }
  }

  return results;
}

// Read and escape content for JS string
function readAndEscape(filepath) {
  const content = readFileSync(filepath, 'utf-8');
  // Use JSON.stringify to properly escape the string
  return JSON.stringify(content);
}

// Find all .lp files in the ASP root
const lpFiles = findLpFiles(aspRoot);

// Sort for consistent output
lpFiles.sort((a, b) => a.path.localeCompare(b.path));

// Generate a map from path -> content for easy lookup
// We inline the content directly to avoid unused FFI export warnings
const mapEntries = lpFiles
  .map(({ path, fullPath }) => {
    return `  ${JSON.stringify(path)}: ${readAndEscape(fullPath)}`;
  })
  .join(',\n');

// Generate the JS module
const output = `// Auto-generated by scripts/embed-lp.js - do not edit manually
// Run 'npm run embed-lp' to regenerate

// Map from file path to content for easy lookup
export const lpFiles = {
${mapEntries}
};
`;

const outputPath = join(projectRoot, 'src', 'EmbeddedPrograms.js');
writeFileSync(outputPath, output);
console.log(`Generated ${outputPath}`);
console.log(`Embedded ${lpFiles.length} .lp files`);
