#!/usr/bin/env node
// Build script to embed .lp files as JavaScript string exports
// This generates src/EmbeddedPrograms.js which can be imported via FFI
// Recursively finds all .lp files and exports them with their relative paths

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { dirname, join, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const aspRoot = join(projectRoot, '..');

// Recursively find all .lp files
function findLpFiles(dir, baseDir = dir) {
  const files = [];
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      // Skip node_modules and hidden directories
      if (!entry.startsWith('.') && entry !== 'node_modules' && entry !== 'web-ui') {
        files.push(...findLpFiles(fullPath, baseDir));
      }
    } else if (entry.endsWith('.lp')) {
      // Get path relative to the ASP root
      const relativePath = relative(baseDir, fullPath);
      files.push({ path: relativePath, fullPath });
    }
  }

  return files;
}

// Read and escape content for JS string
function readAndEscape(filepath) {
  const content = readFileSync(filepath, 'utf-8');
  // Use JSON.stringify to properly escape the string
  return JSON.stringify(content);
}

// Find all .lp files
const lpFiles = findLpFiles(aspRoot);
console.log(`Found ${lpFiles.length} .lp files`);

// Sort files: root files first, then by directory, then by name
lpFiles.sort((a, b) => {
  const aDepth = (a.path.match(/\//g) || []).length;
  const bDepth = (b.path.match(/\//g) || []).length;
  if (aDepth !== bDepth) return aDepth - bDepth;
  return a.path.localeCompare(b.path);
});

// Generate the JS module with an object mapping paths to content
const fileEntries = lpFiles.map(f =>
  `  ${JSON.stringify(f.path)}: ${readAndEscape(f.fullPath)}`
).join(',\n');

// Generate an array of {path, content} objects for PureScript FFI
const fileListEntries = lpFiles.map(f =>
  `  { path: ${JSON.stringify(f.path)}, content: ${readAndEscape(f.fullPath)} }`
).join(',\n');

const output = `// Auto-generated by scripts/embed-lp.js - do not edit manually
// Run 'npm run embed-lp' to regenerate

// Object mapping file paths to their contents
export const embeddedFiles = {
${fileEntries}
};

// Array of {path, content} objects for PureScript FFI
export const embeddedFileList = [
${fileListEntries}
];

// Legacy exports for backwards compatibility
export const botcLp = embeddedFiles["botc.lp"] || "";
export const tbLp = embeddedFiles["tb.lp"] || "";
export const playersLp = embeddedFiles["players.lp"] || "";
export const instLp = embeddedFiles["inst.lp"] || "";
export const typesLp = embeddedFiles["types.lp"] || "";
`;

const outputPath = join(projectRoot, 'src', 'EmbeddedPrograms.js');
writeFileSync(outputPath, output);
console.log(`Generated ${outputPath}`);

// Also log the files found for debugging
for (const f of lpFiles) {
  console.log(`  - ${f.path}`);
}
