-- | FFI bindings for embedded .lp file contents
-- | The JavaScript side is auto-generated by scripts/embed-lp.js
module EmbeddedPrograms
  ( botcLp
  , tbLp
  , playersLp
  , typesLp
  ) where

-- | Core game rules from botc.lp
foreign import botcLp :: String

-- | Trouble Brewing script from tb.lp
foreign import tbLp :: String

-- | Player configuration from players.lp
foreign import playersLp :: String

-- | Type checking constraints from types.lp
foreign import typesLp :: String
